// Portable Equihash (144,5) GPU solver — wgpu host for the WGSL port of
// John Tromp's solver. Exposes the same C ABI as gominer's eqcuda1445, so the
// Go host links either backend unchanged.

use std::cell::Cell;
use std::ffi::c_void;
use std::sync::OnceLock;

const BIG_BUCKETS: u64 = 1 << 12;
const BIG_CAPACITY: u64 = 8688;
const MID_BUCKETS: u64 = 1 << 13;
const MID_CAPACITY: u64 = 4592;
const MAXSOLS: usize = 10;
const PROOFSIZE: usize = 32;
const HEADER_LEN: usize = 180; // algo v1 Equihash input
const NONCE_OFFSET: usize = 140;
const COMPRESSED_SOL_SIZE: usize = 100;
const WORKGROUP: u32 = 256;
const DEFAULT_NTHREADS: u32 = 1 << 20;

// Static workgroup allocations in big_solver.wgsl and the compact shader
// generated by build.rs.  The fast kernel is used where the adapter permits
// it; Apple GPUs use the 32-KiB-compatible compact kernel.
const FAST_COLLISION_WORKGROUP: u32 = 1024;
const FAST_WORKGROUP_STORAGE: u32 = 60_420;
const COMPACT32_COLLISION_WORKGROUP: u32 = 512;
const COMPACT32_WORKGROUP_STORAGE: u32 = 30_212;
const COMPACT16_COLLISION_WORKGROUP: u32 = 256;
const COMPACT16_WORKGROUP_STORAGE: u32 = 16_368;

const BIG_SLOTS: u64 = BIG_BUCKETS * BIG_CAPACITY;
const MID_SLOTS: u64 = MID_BUCKETS * MID_CAPACITY;

// ---------------- blake2b host side (u64 native) ----------------

const IV: [u64; 8] = [
    0x6a09e667f3bcc908,
    0xbb67ae8584caa73b,
    0x3c6ef372fe94f82b,
    0xa54ff53a5f1d36f1,
    0x510e527fade682d1,
    0x9b05688c2b3e6c1f,
    0x1f83d9abfb41bd6b,
    0x5be0cd19137e2179,
];

const SIGMA: [[usize; 16]; 12] = [
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    [14, 10, 4, 8, 9, 15, 13, 6, 1, 12, 0, 2, 11, 7, 5, 3],
    [11, 8, 12, 0, 5, 2, 15, 13, 10, 14, 3, 6, 7, 1, 9, 4],
    [7, 9, 3, 1, 13, 12, 11, 14, 2, 6, 5, 10, 4, 0, 15, 8],
    [9, 0, 5, 7, 2, 4, 10, 15, 14, 1, 11, 12, 6, 8, 3, 13],
    [2, 12, 6, 10, 0, 11, 8, 3, 4, 13, 7, 5, 15, 14, 1, 9],
    [12, 5, 1, 15, 14, 13, 4, 10, 0, 7, 6, 3, 9, 2, 8, 11],
    [13, 11, 7, 14, 12, 1, 3, 9, 5, 0, 15, 4, 8, 6, 2, 10],
    [6, 15, 14, 9, 11, 3, 0, 8, 12, 2, 13, 7, 1, 4, 10, 5],
    [10, 2, 8, 4, 7, 6, 1, 5, 15, 11, 9, 14, 3, 12, 13, 0],
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    [14, 10, 4, 8, 9, 15, 13, 6, 1, 12, 0, 2, 11, 7, 5, 3],
];

fn blake2b_compress(h: &mut [u64; 8], block: &[u8], counter: u64, last: bool) {
    let mut m = [0u64; 16];
    for (i, w) in m.iter_mut().enumerate() {
        *w = u64::from_le_bytes(block[8 * i..8 * i + 8].try_into().unwrap());
    }
    let mut v = [0u64; 16];
    v[..8].copy_from_slice(h);
    v[8..].copy_from_slice(&IV);
    v[12] ^= counter;
    if last {
        v[14] = !v[14];
    }
    macro_rules! g {
        ($r:expr, $i:expr, $a:expr, $b:expr, $c:expr, $d:expr) => {
            v[$a] = v[$a].wrapping_add(v[$b]).wrapping_add(m[SIGMA[$r][2 * $i]]);
            v[$d] = (v[$d] ^ v[$a]).rotate_right(32);
            v[$c] = v[$c].wrapping_add(v[$d]);
            v[$b] = (v[$b] ^ v[$c]).rotate_right(24);
            v[$a] = v[$a]
                .wrapping_add(v[$b])
                .wrapping_add(m[SIGMA[$r][2 * $i + 1]]);
            v[$d] = (v[$d] ^ v[$a]).rotate_right(16);
            v[$c] = v[$c].wrapping_add(v[$d]);
            v[$b] = (v[$b] ^ v[$c]).rotate_right(63);
        };
    }
    for r in 0..12 {
        g!(r, 0, 0, 4, 8, 12);
        g!(r, 1, 1, 5, 9, 13);
        g!(r, 2, 2, 6, 10, 14);
        g!(r, 3, 3, 7, 11, 15);
        g!(r, 4, 0, 5, 10, 15);
        g!(r, 5, 1, 6, 11, 12);
        g!(r, 6, 2, 7, 8, 13);
        g!(r, 7, 3, 4, 9, 14);
    }
    for i in 0..8 {
        h[i] ^= v[i] ^ v[i + 8];
    }
}

/// blake2b state with the Equihash personalization after absorbing the first
/// 128 header bytes: (h, 52-byte remainder).
fn equihash_midstate(header: &[u8; HEADER_LEN]) -> ([u64; 8], [u8; 52]) {
    let mut param = [0u8; 64];
    param[0] = 54; // digest_length = (512/144)*144/8
    param[2] = 1; // fanout
    param[3] = 1; // depth
    param[48..56].copy_from_slice(b"ZcashPoW");
    param[56..60].copy_from_slice(&144u32.to_le_bytes());
    param[60..64].copy_from_slice(&5u32.to_le_bytes());
    let mut h = IV;
    for i in 0..8 {
        h[i] ^= u64::from_le_bytes(param[8 * i..8 * i + 8].try_into().unwrap());
    }
    blake2b_compress(&mut h, &header[..128], 128, false);
    let mut rem = [0u8; 52];
    rem.copy_from_slice(&header[128..]);
    (h, rem)
}

// ---------------- solution post-processing (ports of solver_details) ----------------

fn duped(prf: &[u32; PROOFSIZE]) -> bool {
    let mut sorted = *prf;
    sorted.sort_unstable();
    sorted.windows(2).any(|w| w[1] <= w[0])
}

fn compress_solution(sol: &[u32; PROOFSIZE]) -> [u8; COMPRESSED_SOL_SIZE] {
    // 32 indices x 25 bits, big-endian bit packing (port of compress_solution)
    let mut out = [0u8; COMPRESSED_SOL_SIZE];
    let mut i = 0usize;
    let mut bits_left = 25u32;
    for b in out.iter_mut() {
        if bits_left >= 8 {
            bits_left -= 8;
            *b = (sol[i] >> bits_left) as u8;
        } else {
            let mut v = (sol[i] << (8 - bits_left)) as u8;
            i += 1;
            bits_left += 25 - 8;
            v |= (sol[i] >> bits_left) as u8;
            *b = v;
        }
    }
    out
}

fn uncompress_solution(sol: &[u8; COMPRESSED_SOL_SIZE]) -> [u32; PROOFSIZE] {
    let mut indices = [0u32; PROOFSIZE];
    for (i, index) in indices.iter_mut().enumerate() {
        for bit in i * 25..(i + 1) * 25 {
            *index = (*index << 1) | u32::from((sol[bit / 8] >> (7 - bit % 8)) & 1);
        }
    }
    indices
}

fn leaf_hash(h: &[u64; 8], rem: &[u8; 52], idx: u32) -> [u8; 18] {
    let mut hh = *h;
    let mut block = [0u8; 128];
    block[..52].copy_from_slice(rem);
    block[52..56].copy_from_slice(&(idx / 3).to_le_bytes());
    blake2b_compress(&mut hh, &block, 184, true);
    let mut digest = [0u8; 56];
    for i in 0..7 {
        digest[8 * i..8 * i + 8].copy_from_slice(&hh[i].to_le_bytes());
    }
    let offset = (idx % 3) as usize * 18;
    digest[offset..offset + 18].try_into().unwrap()
}

fn verify_tree(
    h: &[u64; 8],
    rem: &[u8; 52],
    indices: &[u32],
    round: usize,
) -> Result<[u8; 18], i32> {
    if round == 0 {
        return Ok(leaf_hash(h, rem, indices[0]));
    }
    let half = 1 << (round - 1);
    if indices[0] >= indices[half] {
        return Err(3); // POW_OUT_OF_ORDER
    }
    let left = verify_tree(h, rem, &indices[..half], round - 1)?;
    let right = verify_tree(h, rem, &indices[half..], round - 1)?;
    let mut hash = [0u8; 18];
    for i in 0..hash.len() {
        hash[i] = left[i] ^ right[i];
    }
    let zero_bytes = if round < 5 { round * 3 } else { 18 };
    if hash[..zero_bytes].iter().any(|&byte| byte != 0) {
        return Err(4); // POW_NONZERO_XOR
    }
    Ok(hash)
}

fn verify_solution(header: &[u8], solution: &[u8]) -> i32 {
    if header.len() != HEADER_LEN || solution.len() != COMPRESSED_SOL_SIZE {
        return 1; // POW_HEADER_LENGTH
    }
    let indices = uncompress_solution(solution.try_into().unwrap());
    if duped(&indices) {
        return 2; // POW_DUPLICATE
    }
    let (h, rem) = equihash_midstate(header.try_into().unwrap());
    verify_tree(&h, &rem, &indices, 5).map_or_else(|code| code, |_| 0)
}

// ---------------- wgpu plumbing ----------------

fn instance() -> &'static wgpu::Instance {
    static INSTANCE: OnceLock<wgpu::Instance> = OnceLock::new();
    INSTANCE.get_or_init(|| {
        wgpu::Instance::new(wgpu::InstanceDescriptor {
            backends: wgpu::Backends::PRIMARY, // Vulkan / Metal / DX12
            ..Default::default()
        })
    })
}

fn adapters() -> Vec<wgpu::Adapter> {
    instance()
        .enumerate_adapters(wgpu::Backends::PRIMARY)
        .into_iter()
        .filter(|a| a.get_info().device_type != wgpu::DeviceType::Cpu)
        .collect()
}

thread_local! {
    static ADAPTER_IDX: Cell<u32> = const { Cell::new(0) };
}

pub struct EqSolver {
    device: wgpu::Device,
    queue: wgpu::Queue,
    pipelines: Vec<(wgpu::ComputePipeline, u32, u32)>,
    bind_group: wgpu::BindGroup,
    params_buf: wgpu::Buffer,
    counts: [wgpu::Buffer; 5],
    sols_buf: wgpu::Buffer,
    staging_buf: wgpu::Buffer,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum KernelVariant {
    Fast,
    Compact32,
    Compact16,
}

impl KernelVariant {
    fn select(limits: &wgpu::Limits) -> Result<Self, String> {
        let supports = |workgroup, storage| {
            limits.max_compute_invocations_per_workgroup >= workgroup
                && limits.max_compute_workgroup_size_x >= workgroup
                && limits.max_compute_workgroup_storage_size >= storage
        };
        let requested = std::env::var("EQWGPU_KERNEL").unwrap_or_else(|_| "auto".into());
        let variant = match requested.as_str() {
            "auto" if supports(FAST_COLLISION_WORKGROUP, FAST_WORKGROUP_STORAGE) => Self::Fast,
            "auto" if supports(COMPACT32_COLLISION_WORKGROUP, COMPACT32_WORKGROUP_STORAGE) => {
                Self::Compact32
            }
            "auto" if supports(COMPACT16_COLLISION_WORKGROUP, COMPACT16_WORKGROUP_STORAGE) => {
                Self::Compact16
            }
            "fast" if supports(FAST_COLLISION_WORKGROUP, FAST_WORKGROUP_STORAGE) => Self::Fast,
            "compact32" if supports(COMPACT32_COLLISION_WORKGROUP, COMPACT32_WORKGROUP_STORAGE) => {
                Self::Compact32
            }
            "compact16" if supports(COMPACT16_COLLISION_WORKGROUP, COMPACT16_WORKGROUP_STORAGE) => {
                Self::Compact16
            }
            "auto" | "fast" | "compact32" | "compact16" => {
                return Err(format!(
                    "{requested} kernel exceeds adapter limits: compute invocations {}, workgroup storage {} bytes",
                    limits.max_compute_invocations_per_workgroup,
                    limits.max_compute_workgroup_storage_size,
                ));
            }
            _ => {
                return Err(format!(
                    "unknown EQWGPU_KERNEL={requested:?}; use auto, fast, compact32, or compact16"
                ));
            }
        };
        Ok(variant)
    }

    fn shader(self) -> &'static str {
        match self {
            Self::Fast => include_str!("big_solver.wgsl"),
            Self::Compact32 => {
                include_str!(concat!(env!("OUT_DIR"), "/big_solver_compact32.wgsl"))
            }
            Self::Compact16 => {
                include_str!(concat!(env!("OUT_DIR"), "/big_solver_compact16.wgsl"))
            }
        }
    }

    fn collision_dispatches(self) -> (u32, u32) {
        match self {
            Self::Fast => ((BIG_BUCKETS * 4) as u32, 1),
            Self::Compact32 => ((BIG_BUCKETS * 8) as u32, 1),
            Self::Compact16 => ((BIG_BUCKETS * 8) as u32, 2),
        }
    }

    fn workgroup_storage(self) -> u32 {
        match self {
            Self::Fast => FAST_WORKGROUP_STORAGE,
            Self::Compact32 => COMPACT32_WORKGROUP_STORAGE,
            Self::Compact16 => COMPACT16_WORKGROUP_STORAGE,
        }
    }
}

const SOLS_BYTES: u64 = 4 + (MAXSOLS * PROOFSIZE * 4) as u64;

fn dispatch_size(nthreads: u32, max_workgroups: u32) -> Result<(u32, u32), String> {
    let requested = if nthreads == 0 {
        DEFAULT_NTHREADS
    } else {
        nthreads
    };
    let workgroups = requested.div_ceil(WORKGROUP);
    if workgroups > max_workgroups {
        return Err(format!(
            "worksize {requested} needs {workgroups} workgroups; adapter limit is {max_workgroups}"
        ));
    }
    let rounded = workgroups
        .checked_mul(WORKGROUP)
        .ok_or_else(|| format!("worksize {requested} overflows after workgroup rounding"))?;
    Ok((rounded, workgroups))
}

fn create_solver(nthreads: u32) -> Result<EqSolver, String> {
    let all = adapters();
    let idx = ADAPTER_IDX.with(|c| c.get()) as usize;
    let adapter = all.get(idx).ok_or_else(|| format!("no adapter {idx}"))?;
    let adapter_limits = adapter.limits();
    let variant = KernelVariant::select(&adapter_limits)?;
    let (nthreads, digit_h_workgroups) = dispatch_size(
        nthreads,
        adapter_limits.max_compute_workgroups_per_dimension,
    )?;

    let (device, queue) = pollster::block_on(adapter.request_device(
        &wgpu::DeviceDescriptor {
            label: Some("eqwgpu1445"),
            required_features: wgpu::Features::empty(),
            required_limits: adapter_limits,
            memory_hints: wgpu::MemoryHints::Performance,
        },
        None,
    ))
    .map_err(|e| e.to_string())?;

    let module = device.create_shader_module(wgpu::ShaderModuleDescriptor {
        label: Some("equihash solver"),
        source: wgpu::ShaderSource::Wgsl(variant.shader().into()),
    });
    let storage = |binding, read_only| wgpu::BindGroupLayoutEntry {
        binding,
        visibility: wgpu::ShaderStages::COMPUTE,
        ty: wgpu::BindingType::Buffer {
            ty: wgpu::BufferBindingType::Storage { read_only },
            has_dynamic_offset: false,
            min_binding_size: None,
        },
        count: None,
    };
    let bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
        label: None,
        entries: &[
            storage(0, true),
            storage(1, false),
            storage(2, false),
            storage(3, false),
            storage(4, false),
            storage(5, false),
            storage(6, false),
            storage(7, false),
            storage(8, false),
            storage(9, false),
            storage(10, false),
            storage(11, false),
        ],
    });
    let layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
        label: None,
        bind_group_layouts: &[&bgl],
        push_constant_ranges: &[],
    });

    let buf = |label: &str, size: u64, usage| {
        device.create_buffer(&wgpu::BufferDescriptor {
            label: Some(label),
            size,
            usage,
            mapped_at_creation: false,
        })
    };
    use wgpu::BufferUsages as U;
    let params_buf = buf("params", 29 * 4, U::STORAGE | U::COPY_DST);
    let big0 = buf("big0", BIG_SLOTS * 4 * 4, U::STORAGE);
    let big1 = buf("big1", MID_SLOTS * 4 * 4, U::STORAGE);
    let big2 = buf("big2", BIG_SLOTS * 4 * 4, U::STORAGE);
    let leaves = buf("leaves", BIG_SLOTS * 4, U::STORAGE);
    let parents1 = buf("parents1", MID_SLOTS * 2 * 4, U::STORAGE);
    let counts = [
        buf("counts0", BIG_BUCKETS * 4, U::STORAGE | U::COPY_DST),
        buf("counts1", MID_BUCKETS * 4, U::STORAGE | U::COPY_DST),
        buf("counts2", BIG_BUCKETS * 4, U::STORAGE | U::COPY_DST),
        buf("counts3", MID_BUCKETS * 4, U::STORAGE | U::COPY_DST),
        buf("counts4", BIG_BUCKETS * 4, U::STORAGE | U::COPY_DST),
    ];
    let sols_buf = buf("sols", SOLS_BYTES, U::STORAGE | U::COPY_DST | U::COPY_SRC);
    let staging_buf = buf("staging", SOLS_BYTES, U::MAP_READ | U::COPY_DST);

    let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: None,
        layout: &bgl,
        entries: &[
            wgpu::BindGroupEntry {
                binding: 0,
                resource: params_buf.as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 1,
                resource: big0.as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 2,
                resource: big1.as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 3,
                resource: big2.as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 4,
                resource: leaves.as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 5,
                resource: parents1.as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 6,
                resource: counts[0].as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 7,
                resource: counts[1].as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 8,
                resource: counts[2].as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 9,
                resource: counts[3].as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 10,
                resource: counts[4].as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 11,
                resource: sols_buf.as_entire_binding(),
            },
        ],
    });

    let mk_pipeline = |shader: &wgpu::ShaderModule, entry: &str, round: Option<u32>| {
        let mut constants =
            std::collections::HashMap::from([("NTHREADS".to_string(), nthreads as f64)]);
        if let Some(r) = round {
            constants.insert("ROUND".to_string(), r as f64);
        }
        device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some(entry),
            layout: Some(&layout),
            module: shader,
            entry_point: entry,
            compilation_options: wgpu::PipelineCompilationOptions {
                constants: &constants,
                zero_initialize_workgroup_memory: false,
                ..Default::default()
            },
            cache: None,
        })
    };
    let mut pipelines = vec![(mk_pipeline(&module, "digitH", None), digit_h_workgroups, 1)];
    let (collision_dispatches_x, collision_dispatches_y) = variant.collision_dispatches();
    for r in 1..=4 {
        pipelines.push((
            mk_pipeline(&module, "digitR", Some(r)),
            collision_dispatches_x,
            collision_dispatches_y,
        ));
    }
    pipelines.push((
        mk_pipeline(&module, "digitK", None),
        (BIG_BUCKETS * 4) as u32,
        1,
    ));

    let info = adapter.get_info();
    let final_workgroup = if variant == KernelVariant::Compact32 {
        512
    } else if variant == KernelVariant::Compact16 {
        256
    } else {
        1024
    };
    eprintln!(
        "eqwgpu1445: {} ({:?}), {:?} kernel ({} bytes workgroup storage), {}-thread digitK",
        info.name,
        info.backend,
        variant,
        variant.workgroup_storage(),
        final_workgroup,
    );

    Ok(EqSolver {
        device,
        queue,
        pipelines,
        bind_group,
        params_buf,
        counts,
        sols_buf,
        staging_buf,
    })
}

fn solve(
    s: &EqSolver,
    header: &[u8],
    nonce: u32,
    mut on_solution: impl FnMut(&[u8; COMPRESSED_SOL_SIZE]) -> bool,
) -> i32 {
    if header.len() != HEADER_LEN {
        // ponytail: only the 180-byte algo-v1 header is supported (the only
        // live format); generalize the remainder handling if EXCC forks again
        return -1;
    }
    let mut hdr = [0u8; HEADER_LEN];
    hdr.copy_from_slice(header);
    hdr[NONCE_OFFSET..NONCE_OFFSET + 4].copy_from_slice(&nonce.to_le_bytes());

    let (h, rem) = equihash_midstate(&hdr);
    let mut params = [0u8; 29 * 4];
    for i in 0..8 {
        params[8 * i..8 * i + 8].copy_from_slice(&h[i].to_le_bytes());
    }
    params[64..116].copy_from_slice(&rem);
    s.queue.write_buffer(&s.params_buf, 0, &params);
    s.queue.write_buffer(&s.sols_buf, 0, &[0u8; 4]); // reset nsols

    let mut encoder = s.device.create_command_encoder(&Default::default());
    for count in &s.counts {
        encoder.clear_buffer(count, 0, None);
    }
    {
        let mut pass = encoder.begin_compute_pass(&Default::default());
        pass.set_bind_group(0, &s.bind_group, &[]);
        for (pipeline, workgroups_x, workgroups_y) in &s.pipelines {
            pass.set_pipeline(pipeline);
            pass.dispatch_workgroups(*workgroups_x, *workgroups_y, 1);
        }
    }
    encoder.copy_buffer_to_buffer(&s.sols_buf, 0, &s.staging_buf, 0, SOLS_BYTES);
    s.queue.submit([encoder.finish()]);

    let slice = s.staging_buf.slice(..);
    slice.map_async(wgpu::MapMode::Read, |_| {});
    s.device.poll(wgpu::Maintain::Wait);
    let found;
    {
        let data = slice.get_mapped_range();
        let nsols = u32::from_le_bytes(data[0..4].try_into().unwrap()).min(MAXSOLS as u32) as usize;
        let mut n = 0;
        'outer: for i in 0..nsols {
            let mut prf = [0u32; PROOFSIZE];
            for (j, w) in prf.iter_mut().enumerate() {
                let o = 4 + (i * PROOFSIZE + j) * 4;
                *w = u32::from_le_bytes(data[o..o + 4].try_into().unwrap());
            }
            if duped(&prf) {
                continue;
            }
            n += 1;
            if on_solution(&compress_solution(&prf)) {
                break 'outer;
            }
        }
        found = n;
    }
    s.staging_buf.unmap();
    found
}

// ---------------- C ABI (matches eqcuda1445.h) ----------------

type SolutionCb = unsafe extern "C" fn(user_data: *mut c_void, solution: *mut c_void) -> i32;

/// # Safety
/// Called from C; returns an opaque solver handle or NULL.
#[no_mangle]
pub unsafe extern "C" fn eq_create(nthreads: u32) -> *mut EqSolver {
    match std::panic::catch_unwind(|| create_solver(nthreads)) {
        Ok(Ok(s)) => Box::into_raw(Box::new(s)),
        Ok(Err(e)) => {
            eprintln!("eqwgpu1445: {e}");
            std::ptr::null_mut()
        }
        Err(_) => {
            eprintln!("eqwgpu1445: panic in eq_create");
            std::ptr::null_mut()
        }
    }
}

/// # Safety
/// `solver` must come from eq_create.
#[no_mangle]
pub unsafe extern "C" fn eq_destroy(solver: *mut EqSolver) {
    if !solver.is_null() {
        let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            drop(Box::from_raw(solver));
        }));
    }
}

/// # Safety
/// `solver` from eq_create; `header` points to `header_len` readable bytes.
#[no_mangle]
pub unsafe extern "C" fn eq_solve(
    solver: *mut EqSolver,
    header: *const c_void,
    header_len: u32,
    nonce: u32,
    on_solution: Option<SolutionCb>,
    user_data: *mut c_void,
) -> i32 {
    if solver.is_null() || header.is_null() {
        return -1;
    }
    let s = &*solver;
    let hdr = std::slice::from_raw_parts(header as *const u8, header_len as usize);
    let res = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        solve(s, hdr, nonce, |csol| {
            if let Some(cb) = on_solution {
                cb(user_data, csol.as_ptr() as *mut c_void) != 0
            } else {
                false
            }
        })
    }));
    match res {
        Ok(n) => n,
        Err(_) => {
            eprintln!("eqwgpu1445: panic in eq_solve");
            -3
        }
    }
}

/// # Safety
/// `header` points to `header_len` readable bytes and `solution` to 100 bytes.
#[no_mangle]
pub unsafe extern "C" fn equihash_verify_c(
    header: *const u8,
    header_len: u32,
    solution: *const u8,
) -> i32 {
    if header.is_null() || solution.is_null() || header_len as usize != HEADER_LEN {
        return -1;
    }
    std::panic::catch_unwind(|| {
        verify_solution(
            std::slice::from_raw_parts(header, HEADER_LEN),
            std::slice::from_raw_parts(solution, COMPRESSED_SOL_SIZE),
        )
    })
    .unwrap_or(-1)
}

#[no_mangle]
pub extern "C" fn eq_adapter_count() -> u32 {
    std::panic::catch_unwind(|| adapters().len() as u32).unwrap_or(0)
}

/// # Safety
/// `buf` points to `len` writable bytes; writes a NUL-terminated name.
#[no_mangle]
pub unsafe extern "C" fn eq_adapter_name(index: u32, buf: *mut u8, len: u32) -> i32 {
    if buf.is_null() || len == 0 {
        return -1;
    }
    std::panic::catch_unwind(|| {
        let all = adapters();
        let Some(a) = all.get(index as usize) else {
            return -1;
        };
        let info = a.get_info();
        let name = format!("{} ({:?})", info.name, info.backend);
        let bytes = name.as_bytes();
        let n = bytes.len().min(len as usize - 1);
        std::ptr::copy_nonoverlapping(bytes.as_ptr(), buf, n);
        *buf.add(n) = 0;
        0
    })
    .unwrap_or(-1)
}

#[no_mangle]
pub extern "C" fn eq_set_adapter(index: u32) {
    let _ = std::panic::catch_unwind(|| ADAPTER_IDX.with(|c| c.set(index)));
}

// ---------------- tests ----------------

#[cfg(test)]
mod tests {
    use super::*;

    fn validate_shader(source: &str, variant: &str, entry_points: &[(&str, Option<u32>)]) {
        let module = naga::front::wgsl::parse_str(source).unwrap_or_else(|e| {
            panic!("parse {variant} solver WGSL:\n{}", e.emit_to_string(source))
        });
        let info = naga::valid::Validator::new(
            naga::valid::ValidationFlags::all(),
            naga::valid::Capabilities::default(),
        )
        .validate(&module)
        .unwrap_or_else(|e| {
            panic!(
                "validate {variant} solver WGSL:\n{}",
                e.emit_to_string(source)
            )
        });
        for &(entry_point, round) in entry_points {
            let mut constants = naga::back::PipelineConstants::from([(
                "NTHREADS".to_string(),
                DEFAULT_NTHREADS as f64,
            )]);
            if let Some(round) = round {
                constants.insert("ROUND".to_string(), round as f64);
            }
            let (module, info) =
                naga::back::pipeline_constants::process_overrides(&module, &info, &constants)
                    .unwrap_or_else(|e| panic!("resolve {variant} {entry_point} overrides: {e}"));
            let pipeline = naga::back::spv::PipelineOptions {
                shader_stage: naga::ShaderStage::Compute,
                entry_point: entry_point.to_string(),
            };
            naga::back::spv::write_vec(&module, &info, &Default::default(), Some(&pipeline))
                .unwrap_or_else(|e| panic!("compile {variant} {entry_point} to SPIR-V: {e}"));

            let msl_options = naga::back::msl::Options {
                lang_version: (3, 0),
                zero_initialize_workgroup_memory: false,
                ..Default::default()
            };
            naga::back::msl::write_string(&module, &info, &msl_options, &Default::default())
                .unwrap_or_else(|e| panic!("compile {variant} {entry_point} to MSL: {e}"));
        }
    }

    #[test]
    fn shaders_validate_and_compile() {
        let collision_entries = [
            ("digitH", None),
            ("digitR", Some(1)),
            ("digitR", Some(2)),
            ("digitR", Some(3)),
            ("digitR", Some(4)),
            ("digitK", None),
        ];
        validate_shader(KernelVariant::Fast.shader(), "fast", &collision_entries);
        validate_shader(
            KernelVariant::Compact32.shader(),
            "compact32",
            &collision_entries,
        );
        validate_shader(
            KernelVariant::Compact16.shader(),
            "compact16",
            &collision_entries,
        );
    }

    fn decode_hex<const N: usize>(value: &str) -> [u8; N] {
        assert_eq!(value.len(), N * 2);
        std::array::from_fn(|i| u8::from_str_radix(&value[i * 2..i * 2 + 2], 16).unwrap())
    }

    #[test]
    fn verifier_accepts_known_block_and_rejects_corruption() {
        // EXCC mainnet block 616802, independently accepted by the CUDA verifier.
        let header = decode_hex::<HEADER_LEN>(concat!(
            "050000002a27d50432c7585b1435ca5ec904266a3246040860860fd1c2038e69",
            "450800006e4497ec71b812ffe8bb51f207b028ad19d8f01a70a2af25b6c8863b",
            "ece08588afdfc326ac34ec2d2c0e3cadc868d3d5214b7a001334ddcb2ba3001e",
            "fbf32ca80100385d3d9bee0f05000200f29d0000cf25461e0af5555c00000000",
            "626909003d11000043b5e6608490310000000000000000003750d39100000000",
            "0000000000000000000000000000000005000000"
        ));
        let solution = decode_hex::<COMPRESSED_SOL_SIZE>(concat!(
            "0389234e87650cbcfc6b50c0e1d876f6b0bd3d53f1159c580e3226af7bf2cc66",
            "30179b2355d6791ca414cc72636f23afb0d20f6e4798db719e23343afb11f330",
            "b25fd9fef1d046c9983c222be1193fd0da8bbc23be9b5d74d6f543ed6b65544f",
            "ccf479d8"
        ));
        assert_eq!(verify_solution(&header, &solution), 0);
        assert_eq!(
            unsafe { equihash_verify_c(header.as_ptr(), HEADER_LEN as u32, solution.as_ptr()) },
            0
        );

        let mut corrupt = solution;
        corrupt[0] ^= 0x80;
        assert_ne!(verify_solution(&header, &corrupt), 0);
    }

    #[test]
    fn abi_and_dispatch_limits_are_checked() {
        assert_eq!(dispatch_size(1, 1).unwrap(), (WORKGROUP, 1));
        assert!(dispatch_size(WORKGROUP + 1, 1).is_err());
        assert!(dispatch_size(u32::MAX, 65_535).is_err());
        assert_eq!(unsafe { eq_adapter_name(0, std::ptr::null_mut(), 0) }, -1);
        assert_eq!(
            unsafe { equihash_verify_c(std::ptr::null(), 0, std::ptr::null()) },
            -1
        );
    }

    #[test]
    fn gpu_solutions_verify() {
        let mut header = [0x42u8; HEADER_LEN];
        let s = create_solver(0).expect("create solver");
        let mut total = 0;
        for nonce in 0u32..10 {
            header[NONCE_OFFSET..NONCE_OFFSET + 4].copy_from_slice(&nonce.to_le_bytes());
            let (h, rem) = equihash_midstate(&header);
            let n = solve(&s, &header, nonce, |csol| {
                let idxs = uncompress_solution(csol);
                let mut sorted = idxs;
                sorted.sort_unstable();
                assert!(sorted.windows(2).all(|pair| pair[0] != pair[1]));
                assert_eq!(verify_tree(&h, &rem, &idxs, 5), Ok([0u8; 18]));
                false
            });
            assert!(n >= 0, "solve failed: {n}");
            total += n;
        }
        // ~2 solutions per nonce expected; 10 nonces with none would be
        // astronomically unlikely
        assert!(total > 0, "no solutions found in 10 nonces");
        println!("verified {total} solutions over 10 nonces");
    }

    // Run explicitly when tuning a backend:
    // cargo test --release gpu_benchmark -- --ignored --nocapture
    #[test]
    #[ignore]
    fn gpu_benchmark() {
        let attempts = std::env::var("EQWGPU_BENCH_NONCES")
            .ok()
            .and_then(|value| value.parse::<u32>().ok())
            .unwrap_or(100);
        let threads = std::env::var("EQWGPU_BENCH_THREADS")
            .ok()
            .and_then(|value| value.parse::<u32>().ok())
            .unwrap_or(0);
        let header = [0x42u8; HEADER_LEN];
        let s = create_solver(threads).expect("create solver");

        // Exclude pipeline compilation, allocation, and the first submission.
        assert!(solve(&s, &header, 0, |_| false) >= 0);
        let started = std::time::Instant::now();
        let mut solutions = 0i64;
        for nonce in 1..=attempts {
            let found = solve(&s, &header, nonce, |_| false);
            assert!(found >= 0, "solve failed: {found}");
            solutions += i64::from(found);
        }
        let elapsed = started.elapsed().as_secs_f64();
        println!(
            "{attempts} nonces at {} threads, {solutions} solutions in {elapsed:.3}s: {:.3} nonce/s, {:.3} Sol/s",
            if threads == 0 { DEFAULT_NTHREADS } else { threads },
            f64::from(attempts) / elapsed,
            solutions as f64 / elapsed,
        );
    }

    // Splits the command buffer and waits after every dispatch. This is not a
    // throughput benchmark; it is a diagnostic for choosing the next kernel
    // to optimize when native timestamp queries are unavailable.
    #[test]
    #[ignore]
    fn gpu_stage_profile() {
        let attempts = std::env::var("EQWGPU_PROFILE_NONCES")
            .ok()
            .and_then(|value| value.parse::<u32>().ok())
            .unwrap_or(20);
        let header = [0x42u8; HEADER_LEN];
        let s = create_solver(0).expect("create solver");
        assert!(solve(&s, &header, 0, |_| false) >= 0);

        let names = [
            "digitH", "digitR1", "digitR2", "digitR3", "digitR4", "digitK",
        ];
        let mut stage_times = vec![std::time::Duration::ZERO; s.pipelines.len()];
        let mut reset_time = std::time::Duration::ZERO;

        for nonce in 1..=attempts {
            let mut hdr = header;
            hdr[NONCE_OFFSET..NONCE_OFFSET + 4].copy_from_slice(&nonce.to_le_bytes());
            let (h, rem) = equihash_midstate(&hdr);
            let mut params = [0u8; 29 * 4];
            for i in 0..8 {
                params[8 * i..8 * i + 8].copy_from_slice(&h[i].to_le_bytes());
            }
            params[64..116].copy_from_slice(&rem);
            s.queue.write_buffer(&s.params_buf, 0, &params);
            s.queue.write_buffer(&s.sols_buf, 0, &[0u8; 4]);

            let started = std::time::Instant::now();
            let mut encoder = s.device.create_command_encoder(&Default::default());
            for count in &s.counts {
                encoder.clear_buffer(count, 0, None);
            }
            s.queue.submit([encoder.finish()]);
            s.device.poll(wgpu::Maintain::Wait);
            reset_time += started.elapsed();

            for (stage, (pipeline, workgroups_x, workgroups_y)) in s.pipelines.iter().enumerate() {
                let started = std::time::Instant::now();
                let mut encoder = s.device.create_command_encoder(&Default::default());
                {
                    let mut pass = encoder.begin_compute_pass(&Default::default());
                    pass.set_bind_group(0, &s.bind_group, &[]);
                    pass.set_pipeline(pipeline);
                    pass.dispatch_workgroups(*workgroups_x, *workgroups_y, 1);
                }
                s.queue.submit([encoder.finish()]);
                s.device.poll(wgpu::Maintain::Wait);
                stage_times[stage] += started.elapsed();
            }
        }

        let divisor = f64::from(attempts);
        println!(
            "reset: {:.3} ms/nonce",
            reset_time.as_secs_f64() * 1000.0 / divisor
        );
        for (name, elapsed) in names.into_iter().zip(stage_times) {
            println!(
                "{name}: {:.3} ms/nonce",
                elapsed.as_secs_f64() * 1000.0 / divisor
            );
        }
    }
}
